# Generated by Django 2.0.6 on 2018-07-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profilemodel_progresslevel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilemodel',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='profilemodel',
            name='progressLevel',
        ),
        migrations.AddField(
            model_name='profilemodel',
            name='Class',
            field=models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE'), ('FOUR', 'FOUR'), ('FIVE', 'FIVE'), ('SIX', 'SIX'), ('SEVEN', 'SEVEN'), ('EIGHT', 'EIGHT')], default='EIGHT', help_text='Choose between lecture or student', max_length=255),
        ),
    ]
