# Generated by Django 2.0.6 on 2018-08-01 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180731_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='Class',
            field=models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE'), ('FOUR', 'FOUR'), ('FIVE', 'FIVE'), ('SIX', 'SIX'), ('SEVEN', 'SEVEN'), ('EIGHT', 'EIGHT')], default='EIGHT', help_text='Enter the current class you are in', max_length=255),
        ),
    ]
