# Generated by Django 2.0.6 on 2018-08-08 05:56

from django.db import migrations, models
import graphs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PdfResources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf', models.FileField(blank=True, default='', max_length=300, upload_to=graphs.models.study, verbose_name='pdf_file')),
                ('Class', models.CharField(choices=[('ONE', 'ONE'), ('TWO', 'TWO'), ('THREE', 'THREE'), ('FOUR', 'FOUR'), ('FIVE', 'FIVE'), ('SIX', 'SIX'), ('SEVEN', 'SEVEN'), ('EIGHT', 'EIGHT')], default='EIGHT', help_text='Enter the current class you are in', max_length=255)),
                ('subject', models.CharField(blank=True, default='', help_text='Enter the subject of the book', max_length=140)),
            ],
            options={
                'db_table': 'pdf_',
            },
        ),
    ]
